### ISSUE TITLE
Pushing start button does nothing

### ISSUE THREAD

**Issue by BAquea** [jonnydark/wanikani-burn#20] opened 2017-06-23 02:27 UTC
I installed the script and it shows up on the homepage but I can't get it to actually work. Pushing the start button does nothing. I also don't understand where I need to input my API key in the script.

**Comment by ashfleeburgooben** [comment] 2017-06-23 14:23
Just noticed that I am also experiencing this same issue, the difference being mine has been installed and working for a long time.  BAquea, there is usually no need to input the API manually.  The script does it automatically for you.

It definitely isn't working though.  It just sits at the "Start" screen and doesn't advance past that.

**Comment by jj-tetraquark** [comment] 2017-07-03 07:23
Hey, sorry to leave you hanging. I think the issue was caused by an external library that I use moving and that should now be fixed as of pull request #21 

If you update your script from here or greasyfork, it should now be fixed. Let me know if it doesn't

**Comment by ashfleeburgooben** [comment] 2017-07-03 07:26
That fixed it for me.  You're a good man!  Thanks!

**Comment by jj-tetraquark** [comment] 2017-07-04 10:04
Based on @ashfleeburgooben's response, I'm closing this ticket. If you're still having issues after upgrading @BAquea, please do reopen.

**Closed as completed** 2017-07-04 12:47 UTC
