### ISSUE TITLE
hovering over items broken

### ISSUE THREAD

**Issue by Amenophyckxs** [jonnydark/wanikani-burn#7] opened 2016-06-11 16:21 UTC
With the script enabled, whenever i hover over the number of apprentice, guru, master, enlightened and burned items, the window that appears is distorted.
here is a screenshot of how it looks with the script disabled:
![image](https://cloud.githubusercontent.com/assets/6186154/15986153/fabfd228-3000-11e6-96bc-b20fabc3fd4d.png)

and this is how it appears with the script enabled:
![image](https://cloud.githubusercontent.com/assets/6186154/15986160/35bce302-3001-11e6-993d-c7fdb17f4dc7.png)
it basically stretches it really wide and i cant even get to see the numbers

**Comment by Amenophyckxs** [comment] 2016-06-11 23:23
just noticed it is the same issue as #6 so can ignore this

**Comment by jj-tetraquark** [comment] 2016-06-13 08:09
Duplicate of #6

**Closed as completed by jj-tetraquark** 2016-06-13 08:09 UTC
