### ISSUE TITLE
Start button disappears

### ISSUE THREAD

**Issue by Amenophyckxs** [jonnydark/wanikani-burn#3] opened 2016-06-02 22:56 UTC
When i open the dashboard, i see the window appear with "start" in the middle and then half a second later, the window collapses and the "start" disappears.
I'm left with this: http://prntscr.com/bbni2g
i have tried to disable all other userscripts one by one, but that did not fix it.
on windows 10 - chrome 50.0.2661.102 m (64-bit)

**Comment by jj-tetraquark** [comment] 2016-06-07 20:49
Oh interesting this looks quite similar to issue #2 - possibly a duplicate.

As of yet I've been unable to properly reproduce this. Both of you seem to be using a dark theme - I wonder if that that's what's causing the issue.

Can you tell me how you got the dark theme?

**Comment by Amenophyckxs** [comment] 2016-06-08 02:28
Its a userstyle called  wanikani dark that i use with stylish. I tried disabling it before sending this error too,  but that didn't change anything

**Comment by jj-tetraquark** [comment] 2016-06-09 08:47
I need to find out for definite if the widget is being created and exists in the DOM. It's possible it's there and is just incorrectly styled (somehow).

I've made a separate branch which should log a lot of stuff out to the console. If you don't mind, could you uninstall your current version and install from here:

https://github.com/jonnydark/wanikani-burn/raw/bugfix/reviews-not-displaying/WanikaniBurnReviews.user.js

Once you've done that, can you go to https://www.wanikani.com/dashboard, open the console up (F12) and copy out what you get? There should be a bunch of stuff starting with "WKBurnReview: "

I appreciate it's hassle but given that I can't reproduce this error, I don't have many other options to debug it.

**Comment by Amenophyckxs** [comment] 2016-06-09 17:24
This is what i got from console, hope this helps to determine where the
problem lies!

started Wanikani Dashboard Active Topics Panel
VM602:459 script load end
VM603:304 script load end
VM611:955 running dotExpandMulti()
VM611:972 running dotExpandSingle()
VM611:1001 WaniKani DotDotDot Expander: script load end
VM626:50 WKBurnReview: Running!
VM626:50 WKBurnReview: Loading...
VM626:50 WKBurnReview: Checking for wanikana...
VM626:947 Uncaught ReferenceError: wanakana is not defined
VM626:50 WKBurnReview: Checking for wanikana...
VM626:947 Uncaught ReferenceError: wanakana is not defined
VM596:20 START OF WRN
VM602:421 main()
VM602:262 init() start
VM602:284 init() end
VM602:65 checkLevel() start
VM602:101 prev level:  12
VM602:102 cur level:  12
VM602:103 next level:  13
VM602:104 checkLevel() end
VM602:113 shouldDisplay() start
VM602:125 now =  1465492893234
VM602:126 levTime =  1462562587327
VM602:127 rawdur =  10
VM602:128 duration minutes =  10
VM602:143 duration msec =  600000
VM602:145 now - levTime =  2930305907
VM602:153 retval =  0
VM602:155 shouldDisplay() end
VM602:306 checkMilestones()
VM602:216 getTurtleCounts()
VM602:247 raw counts:  102 266 165 506 449
VM602:254 cumulative counts:  1488 1386 1120 955 449
VM602:314 nextMilestones:  [1500,1500,1000,500]
VM602:349 achievements:  [0,0,0,0]
VM602:358 checkMilestones() returning null
VM603:286 pathname:  /dashboard
VM603:288 main()
VM603:269 init() start
VM603:277 init() end
VM603:85 checkLevel() start
VM603:133 prev level:  12
VM603:134 cur level:  12
VM603:135 next level:  13
VM603:136 checkLevel() end
VM603:145 displayLastLevTime()
VM603:159 diffDays    =  33.9
VM603:160 displayType =  1
VM603:31 get fct
VM603:33 WKlvlupImg
VM603:31 get fct
VM603:33 WKlvlupTxt
VM603:31 get fct
VM603:33 search
VM603:31 get fct
VM603:33 WKlvldurTxt
VM622:765 START - WaniKani Item Marker
VM622:776 END - WaniKani Item Marker
VM624:963 START - WaniKani Lattice Extension
VM624:977 END - WaniKani Lattice Extension
VM626:50 WKBurnReview: Checking for wanikana...
VM626:50 WKBurnReview: Getting WaniKana data
VM626:50 WKBurnReview: Initialising the Burn Review widget
VM626:50 WKBurnReview: Getting the review page stylesheet...
VM626:50 WKBurnReview: Undoing conflicting CSS
VM626:50 WKBurnReview: Adding burn review section
VM626:50 WKBurnReview: Getting first burn review
VM626:241 Uncaught TypeError: Cannot read property 'character' of undefined
VM626:50 WKBurnReview: Got the review page document. Extracting styles
VM626:50 WKBurnReview: Adding <link href="
https://cdn.wanikani.com/assets/v03/review/application-0a297e6f1c95314ee53decb231d9055d.css"
media="screen" rel="stylesheet" type="text/css"> to document head
VM626:50 WKBurnReview: Adding <link href="//
fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700"
rel="stylesheet" type="text/css"> to document head
VM622:765 START - WaniKani Item Marker
VM622:776 END - WaniKani Item Marker

**Comment by jj-tetraquark** [comment] 2016-06-10 12:02
Thanks! Ok I think I know what's going wrong. Basically the code has failed to get your wanikani data and is failing ungracefully. I was able to reproduce your issue by using an invalid API key.

The original maintainer of this plugin didn't put in sufficient error checking to confirm that it was able to actually get the data. Also the fact that you have to edit and put in your API key to get it working is absurd. This is something I will fix in a future update.

In order to get this up and running and working for you right now though, do the following:
1. Go to your dashboard, open up the console (F12) and in the prompt type localStorage.clear() and press return. DO NOT RELOAD THE PAGE YET.
2. Go to your Tampermonkey dashboard  and open up the script. Make sure your API key is filled in correctly.
3. Reload the wanikani dashboard. It should hopefully now be working.

If that doesn't work, then just wait until I've fixed the code to handle these errors better :)

**Comment by Amenophyckxs** [comment] 2016-06-10 19:29
well that fucked up my settings i changed with other scripts, like the
entered lines on the celebration script, my marked items, and ultimate
timeline...
I should have thought about that i guess >.<
it does fix the problem with your script. I had the api added but i guess
for some reason it did not refresh and used cache?
whatever it is, it works now...
only a bit shitty i have to go over all other scripts's settings again.

thanks

**Comment by jj-tetraquark** [comment] 2016-06-10 19:43
Oh shit! I'm really sorry! I should have warned you about that! I hope it isn't too much hassle :/

What had happened was that it had somehow got the wrong API key and had built up a cache of burnt that was empty. Because the cache was empty it couldn't display the widget, but because the cache existed, it didn't bother trying to update ever again.

It's stupidly written and it's on my list of things to fix. I'll close this ticket when I've fixed this particular issue :)

Thankyou for helping debug this script and again, apologies for messing up your other scripts.

**Comment by Amenophyckxs** [comment] 2016-06-10 19:51
Ah dont worry too much, it was a good excuse for me to update my gif and
text for the levelup script, which was long overdue.
I do wonder how it got wrong api key info, afaik i never changed it or
requested a new one, so it should have been using the same one since the
start.
oh well :P its fixed now, so im not gonna worry about that anymore
thanks again!

**Comment by jj-tetraquark** [comment] 2016-06-10 19:59
Well shit, I just realised I've ruined that one for myself too....
I'm an idiot.

**Comment by Amenophyckxs** [comment] 2016-06-10 20:00
:D

**Comment by Amenophyckxs** [comment] 2016-06-11 16:25
this is probably useless info, but just letting you know to remove any doubt. I disabled the bugfix version and reinstalled the normal version and that works fine now too, aside from a new bug i found (in both versions) for which i made a  new issue :)
I wont uninstall the bugfix version yet, as it might be needed for you to pinpoint where the problem lies with the new issue

**Comment by jj-tetraquark** [comment] 2016-06-11 19:33
Ah good, that's what I would have expected. The fact the cache got in to
that state in the first place though, is a bug. I'll keep this ticket open
until I've written something to mitigate against it happening again.
That's for reporting this and helping with the diagnosis :)

**Comment by jj-tetraquark** [comment] 2016-06-13 08:08
Confirmed this is a duplicate of issue #2

**Closed as completed by jj-tetraquark** 2016-06-13 08:08 UTC
Labels: bug
