### ISSUE TITLE
No confirmation of answers

### ISSUE THREAD

**Issue by ashfleeburgooben** [jonnydark/wanikani-burn#18] opened 2016-11-24 00:28 UTC
When using WaniKani burn reviews in Chrome text is input but when enter is hit there is no change indicating correct or incorrect answers.  Cursor changes to a red circle with a cross through it.  Seems to be new issue as this used to work correctly.

Did attempt to remove script and reinstall from scratch with no luck.

**Comment by jj-tetraquark** [comment] 2016-11-28 09:15
Yeah I noticed this myself a couple of days ago, though I think I know what the issue is now. I imagine you're experiencing a few other graphical issues too?

The script pulls through the stylesheet from the reviews page and that is what is used to display the correct and incorrect answers. However a recent change in the wanikani codebase has made this break and I believe this is the route of the problem. If I'm right, this should be relatively easy to fix.

**Comment by jj-tetraquark** [comment] 2016-11-28 09:29
I've made a fix for this issue and it's working at my end. If you reinstall the script from GreasyFork or update by some other means to version 2.2.1 this should work for you again. If it doesn't then please do reopen this ticket :)
ありがとう！

**Closed as completed by jj-tetraquark** 2016-11-28 09:29 UTC
Labels: bug

**Comment by ashfleeburgooben** [comment] 2016-11-30 11:25
Working on my end.  Thanks!  I really appreciate this script!  :)

**Comment by ashfleeburgooben** [comment] 2017-01-01 10:37
Just had this issue crop up again.  Not sure if I should make a new issue or not though.  Same sort of change on Wanikani's end perhaps?

**Comment by jj-tetraquark** [comment] 2017-01-03 16:16
The script is still working fine on my end. Can you double check you have installed the latest version of the script (2.2.1) and if it's still not working can you please tell me what browser and OS you are using?

Thanks :)

**Comment by ashfleeburgooben** [comment] 2017-01-05 01:43
Went and tried again today and now everything seems to be working just fine.  Not sure what the issue was, but it seems to be a non-issue.  If that changes I'll let you know but in the meantime, ごめんなさい！

Thanks!
